apiVersion: apps/v1

kind: Deployment

metadata:

  name: stockapp-deployment

spec:

  selector:

    matchLabels:

      app: stockapp

  replicas: 2

  template:

    metadata:

      labels:

        app: stockapp

    spec:

      containers:

      - name: stockapp

        image: rachana456/stockapp:latest

        ports:

        - containerPort: 8080

---

apiVersion: v1

kind: Service

metadata:

  name: stockapp

spec:

  selector:

    app: stockapp

  type: NodePort

  ports:

    - protocol: TCP

      port: 8080

      nodePort: 32001
